# Generated by Django 2.0 on 2019-06-10 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(blank=True, default=None, max_length=30, null=True, unique=True, verbose_name='open id')),
                ('nickname', models.CharField(max_length=50, verbose_name='微信昵称')),
                ('avatarUrl', models.CharField(blank=True, max_length=255, verbose_name='头像')),
                ('country', models.CharField(blank=True, max_length=30, verbose_name='国家')),
                ('province', models.CharField(blank=True, max_length=30, verbose_name='省份')),
                ('city', models.CharField(blank=True, max_length=30, verbose_name='城市')),
                ('gender', models.CharField(choices=[('0', '未知'), ('1', '男'), ('2', '女')], default='0', max_length=1, verbose_name='性别')),
                ('status', models.CharField(choices=[('1', '正常'), ('0', '冻结')], default='normal', max_length=10, verbose_name='状态')),
                ('name', models.CharField(blank=True, default='', max_length=30, verbose_name='真实姓名')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='加入时间')),
            ],
        ),
    ]
