# Generated by Django 2.0 on 2019-06-18 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountmodel',
            options={'verbose_name': '账户', 'verbose_name_plural': '账户'},
        ),
    ]
