# Generated by Django 2.0.1 on 2019-05-31 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='标题')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('cover', models.CharField(max_length=200, verbose_name='封面')),
                ('desc', models.TextField(verbose_name='详情')),
                ('address', models.CharField(max_length=150, verbose_name='地址')),
                ('facilities', models.CharField(max_length=200, verbose_name='设施')),
                ('is_elevator', models.BooleanField(default=False, verbose_name='电梯房')),
                ('has_living_room', models.BooleanField(default=False, verbose_name='客厅房')),
                ('status', models.CharField(choices=[('1', '售卖中'), ('2', '已删除'), ('3', '已售卖')], default='1', max_length=1, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='HouseImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.CharField(max_length=200, verbose_name='图片')),
                ('url', models.CharField(max_length=200, verbose_name='跳转链接')),
                ('status', models.CharField(choices=[('1', '展示中'), ('2', '未展示'), ('3', '已删除')], default='1', max_length=1, verbose_name='状态')),
                ('House_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='house.House', verbose_name='房源')),
            ],
        ),
    ]
