# Generated by Django 2.0 on 2019-06-12 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('house', '0002_house_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(max_length=200, verbose_name='封面图')),
                ('redirect_url', models.CharField(max_length=200, verbose_name='跳转链接')),
                ('desc', models.CharField(default='', max_length=200, null=True, verbose_name='说明')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='加入时间')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
            ],
        ),
    ]
