# Generated by Django 2.0 on 2019-06-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='has_living_room',
        ),
        migrations.AddField(
            model_name='house',
            name='is_apartment',
            field=models.BooleanField(default=False, verbose_name='公寓房'),
        ),
        migrations.AddField(
            model_name='house',
            name='region',
            field=models.CharField(choices=[('0', '不选'), ('1', '罗湖区'), ('2', '福田区'), ('3', '南山区'), ('4', '龙岗区'), ('5', '盐田区'), ('6', '宝安区'), ('7', '光明新区'), ('8', '坪山新区'), ('9', '龙华新区'), ('10', '大鹏新区')], default='0', max_length=20, verbose_name='区域'),
        ),
        migrations.AddField(
            model_name='house',
            name='subway',
            field=models.CharField(choices=[('0', '不选'), ('1', '1号线'), ('2', '2号线'), ('3', '3号线'), ('4', '4号线'), ('5', '5号线'), ('7', '7号线'), ('8', '8号线'), ('9', '9号线'), ('10', '10号线'), ('11', '11号线')], default='0', max_length=20, verbose_name='周边地铁'),
        ),
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.CharField(max_length=150, verbose_name='详细地址'),
        ),
    ]
