# Generated by Django 2.0 on 2019-06-12 13:17

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_auto_20190612_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='desc',
            field=DjangoUeditor.models.UEditorField(verbose_name='详情'),
        ),
    ]
