# Generated by Django 2.0 on 2019-06-13 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_house_house_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='facilities',
            field=models.TextField(default=[], verbose_name='设施'),
        ),
    ]
