# Generated by Django 2.0 on 2019-06-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0008_auto_20190613_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '首页banner', 'verbose_name_plural': '首页banner'},
        ),
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name': '房源', 'verbose_name_plural': '房源'},
        ),
        migrations.AlterModelOptions(
            name='houseimg',
            options={'verbose_name': '房源图片', 'verbose_name_plural': '房源图片'},
        ),
        migrations.AlterField(
            model_name='house',
            name='house_type',
            field=models.CharField(choices=[('0', '不限'), ('1', '单间'), ('2', '合租'), ('3', '一室一厅'), ('4', '两室一厅'), ('5', '其它')], default='1', max_length=20, verbose_name='户型'),
        ),
        migrations.AlterField(
            model_name='house',
            name='region',
            field=models.CharField(choices=[('0', '不限'), ('1', '罗湖区'), ('2', '福田区'), ('3', '南山区'), ('4', '龙岗区'), ('5', '盐田区'), ('6', '宝安区'), ('7', '光明新区'), ('8', '坪山新区'), ('9', '龙华新区'), ('10', '大鹏新区')], default='0', max_length=20, verbose_name='区域'),
        ),
        migrations.AlterField(
            model_name='house',
            name='status',
            field=models.CharField(choices=[('0', '售卖中'), ('1', '已删除'), ('2', '已售卖')], default='0', max_length=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='house',
            name='subway',
            field=models.CharField(choices=[('0', '不限'), ('1', '1号线'), ('2', '2号线'), ('3', '3号线'), ('4', '4号线'), ('5', '5号线'), ('6', '6号线'), ('7', '7号线'), ('8', '8号线'), ('9', '9号线'), ('10', '10号线'), ('11', '11号线')], default='0', max_length=20, verbose_name='周边地铁'),
        ),
    ]
