<<<<<<< HEAD
# Generated by Django 2.0 on 2019-06-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0009_auto_20190618_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='apartment',
            field=models.CharField(choices=[('0', '不限'), ('1', '整租'), ('2', '合租')], default='0', max_length=20, verbose_name='整租/合租'),
        ),
    ]
=======
# Generated by Django 2.0 on 2019-06-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0009_auto_20190618_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='apartment',
            field=models.CharField(choices=[('0', '不限'), ('1', '整租'), ('2', '合租')], default='0', max_length=20, verbose_name='整租/合租'),
        ),
    ]
>>>>>>> c77d35942959f03a1c81eb0afec347e857314f2d
