# Generated by Django 2.0 on 2019-07-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0011_auto_20190620_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='area',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='面积'),
        ),
        migrations.AddField(
            model_name='house',
            name='diraction',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='方向'),
        ),
        migrations.AddField(
            model_name='house',
            name='imgs',
            field=models.TextField(default=[], verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='house',
            name='storey',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='楼层'),
        ),
        migrations.AddField(
            model_name='house',
            name='view_count',
            field=models.CharField(max_length=10, null=True, verbose_name='查看数量'),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_type',
            field=models.CharField(choices=[('0', '不限'), ('1', '整租'), ('2', '合租')], default='0', max_length=20, verbose_name='类型（整租，合租）'),
        ),
    ]
