# Generated by Django 2.0 on 2019-07-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0012_auto_20190709_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={},
        ),
        migrations.AlterField(
            model_name='house',
            name='facilities',
            field=models.TextField(default=[], verbose_name='设施'),
        ),
    ]
