# Generated by Django 2.0 on 2019-07-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0013_auto_20190709_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name': '房源', 'verbose_name_plural': '房源'},
        ),
        migrations.AlterField(
            model_name='house',
            name='view_count',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='查看数量'),
        ),
    ]
