# Generated by Django 2.0 on 2019-07-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0014_auto_20190710_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='apartment',
            field=models.CharField(choices=[('0', '未填写'), ('1', '单间'), ('2', '合租'), ('3', '一室一厅'), ('4', '两室一厅'), ('5', '其它')], default='0', max_length=20, verbose_name='户型'),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_type',
            field=models.CharField(choices=[('0', '未填写'), ('1', '整租'), ('2', '合租')], default='0', max_length=20, verbose_name='类型（整租，合租）'),
        ),
        migrations.AlterField(
            model_name='house',
            name='region',
            field=models.CharField(choices=[('0', '未填写'), ('1', '罗湖区'), ('2', '福田区'), ('3', '南山区'), ('4', '龙岗区'), ('5', '盐田区'), ('6', '宝安区'), ('7', '光明新区'), ('8', '坪山新区'), ('9', '龙华新区'), ('10', '大鹏新区')], default='0', max_length=20, verbose_name='区域'),
        ),
        migrations.AlterField(
            model_name='house',
            name='subway',
            field=models.CharField(choices=[('0', '未填写'), ('1', '1号线'), ('2', '2号线'), ('3', '3号线'), ('4', '4号线'), ('5', '5号线'), ('6', '6号线'), ('7', '7号线'), ('8', '8号线'), ('9', '9号线'), ('10', '10号线'), ('11', '11号线')], default='0', max_length=20, verbose_name='周边地铁'),
        ),
        migrations.AlterField(
            model_name='house',
            name='view_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='查看数量'),
        ),
    ]
