# Generated by Django 2.0 on 2019-06-18 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0002_auto_20190612_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '后台USER', 'verbose_name_plural': '后台USER'},
        ),
    ]
